package mimemagic

var namespaces = []namespace{
	{"http://www.w3.org/2005/Atom", "feed", 4},
	{"http://www.opengis.net/gml/3.2", "gml", 11},
	{"http://www.topografix.com/GPX/1/0", "gpx", 13},
	{"http://www.topografix.com/GPX/1/1", "gpx", 13},
	{"http://www.w3.org/1998/Math/MathML", "math", 23},
	{"http://www.metalinker.org/", "metalink", 25},
	{"urn:ietf:params:xml:ns:metalink", "metalink", 26},
	{"http://www.w3.org/2002/07/owl#", "Ontology", 33},
	{"http://www.w3.org/1999/02/22-rdf-syntax-ns#", "RDF", 58},
	{"http://www.w3.org/2001/SMIL20/Language", "smil", 65},
	{"http://www.w3.org/2005/SMIL21/Language", "smil", 65},
	{"http://www.w3.org/ns/SMIL", "smil", 65},
	{"http://www.opengis.net/kml/2.2", "kml", 84},
	{"http://www.kde.org/standards/kcfg/1.0", "kcfg", 91},
	{"https://www.kde.org/standards/kxmlgui/1.0", "gui", 95},
	{"http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul", "window", 99},
	{"http://www.abisource.com/awml.dtd", "abiword", 192},
	{"http://www.lysator.liu.se/~alla/dia/", "diagram", 244},
	{"http://www.daa.com.au/~james/dia-shape-ns", "shape", 245},
	{"http://www.gribuser.ru/xml/fictionbook/2.0", "FictionBook", 257},
	{"http://www.w3.org/1999/xhtml", "html", 525},
	{"urn:oasis:names:tc:xliff:document:1.1", "xliff", 526},
	{"http://www.w3.org/1999/XSL/Transform", "stylesheet", 531},
	{"http://xspf.org/ns/0/", "playlist", 532},
	{"http://www.w3.org/2000/svg", "svg", 615},
	{"http://schema.omg.org/spec/XMI/2.0", "XMI", 947},
	{"http://schema.omg.org/spec/XMI/2.1", "XMI", 947},
	{"http://www.w3.org/1999/XSL/Format", "root", 948},
}
